### ISSUE TITLE
application.properties messes up my spring boot application port

### ISSUE THREAD

**Issue by don41382** [novuhq/novu-java#117]
Hi guys,

is there any special reason to have a `application.properties` inside of the library? It's detected by my spring boot and uses 8081 instead of 8080.

Cheers,
Felix

**Comment by mayorJAY** [comment]
That's an oversight, it's not needed in the project. This will be fixed in the next release

**Comment by don41382** [comment]
perfect, thanks!

**Comment by RuslanHryn** [comment]
@mayorJAY  Do you know when this fix will be released? it is a significant blocker for those who using spring boot

**Comment by unicodeveloper** [comment]
@don41382 @RuslanHryn I just tagged a new release. Please check it out and retry. https://github.com/novuhq/novu-java/releases/tag/v1.6.0

Thanks for your patience

**Comment by RuslanHryn** [comment]
Thanks a lot!
