### ISSUE TITLE
Getting exception while updating subscriber preferences using java sdk

### ISSUE THREAD

**Issue by prashanth-fbt** [novuhq/novu-java#36]
Exception : org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"message":"Cannot PUT /v1/subscribers/{{subscriber_id}}/preferences/{{template_id}}","error":"Not Found","statusCode":404}"

what I observed is method SDK uses is PUT but in API documentation it uses patch and it is working fine so how to change this to patch in SDK? 

Are any changes coming from new releases or any alternate way to implement this?

**Comment by Basfar** [comment]
@prashanth-fbt Are you interested in picking this up?

**Comment by prashanth-fbt** [comment]
> @prashanth-fbt Are you interested in picking this up?

Yes Am interested.

**Comment by Basfar** [comment]
Alright. Please go ahead. Go to the main branch, fetch the latest, and submit a fresh PR against the main branch.
