### ISSUE TITLE
Not able to use patch supported methods in kotlin using java sdk

### ISSUE THREAD

**Issue by prashanth-fbt** [novuhq/novu-java#41]
Getting below error:

org.springframework.web.client.ResourceAccessException: I/O error on PATCH request for "https://api.novu.co/v1/subscribers/{subscriber_id}/preferences/{template_id}": Invalid HTTP method: PATCH; nested exception is java.net.ProtocolException: Invalid HTTP method: PATCH

Not getting whether it's not supported at the SDK level or at my Kotlin application level.

Any help on this will be useful. Do I need to add any other libraries to support this kind of HTTP method?

**Comment by mayorJAY** [comment]
It appears that PATCH method is not supported out of the box. A request factory needs to be provided.
A fix for this would be in the next release
