### ISSUE TITLE
Refactor Events API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#50]
We want to refactor the Events API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by ChenemiKen** [comment]
Can I work on this?

**Comment by parthasarathy-G76** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by kstv364** [comment]
Hi @mayorJAY , @unicodeveloper , I would like to work on this. Can you please assign this to me?

**Comment by mayorJAY** [comment]
@sccalabr I see you've been assigned an issue already
@ChenemiKen are you available to pick this up ASAP?

**Comment by ChenemiKen** [comment]
Yes I am @mayorJAY

**Comment by mayorJAY** [comment]
I am assigning it to you

**Comment by ChenemiKen** [comment]
Thanks
