### ISSUE TITLE
Refactor Topic API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#51]
We want to refactor the Topics API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by piyushchhabra** [comment]
Would like to pick this up. please assign this to me

**Comment by unicodeveloper** [comment]
Sure. Assigning this to you right away @piyushchhabra

**Comment by unicodeveloper** [comment]
Assigned ⭐
