### ISSUE TITLE
Refactor Notifications API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#52]
We want to refactor the Notifications API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by debanjanc01** [comment]
@mayorJAY is this up for grabs?

**Comment by mayorJAY** [comment]
Yes, let me know if you want it assigned to you

**Comment by debanjanc01** [comment]
> Yes, let me know if you want it assigned to you

Yes, thanks!

**Comment by mayorJAY** [comment]
@debanjanc01 there seems to be no traction on this issue. Are you still working on it?

**Comment by debanjanc01** [comment]
Hey @mayorJAY ,  yes I'm working on it.

**Comment by debanjanc01** [comment]
Hey @mayorJAY , The PR has been raised.
