### ISSUE TITLE
Refactor Integrations API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#56]
We want to refactor the Integrations API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by charan2628** [comment]
Hi @mayorJAY , Can I work on this?

**Comment by mayorJAY** [comment]
Hi @charan2628, I think you've done a very great job so far. You should probably give some other people the opportunity to also contribute. Thank you so much for your contributions

**Comment by charan2628** [comment]
Ok @mayorJAY Thank you

**Comment by unicodeveloper** [comment]
Assigning this to you @sccalabr

**Comment by unicodeveloper** [comment]
Assigned to you now @sccalabr

**Comment by mayorJAY** [comment]
@sccalabr there seems to be no traction on this issue. Are you still working on it?

**Comment by mayorJAY** [comment]
I believe the tests should be in IntegrationsHandlerTest class. You should focus on those tests only. Ensure that they all pass and that's okay
