### ISSUE TITLE
Refactor Workflow API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#58]
We want to refactor the Workflow API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by AnuragNishad12** [comment]
hey @mayorJAY  can u assign this to me ?

**Comment by mayorJAY** [comment]
Sure

**Comment by mayorJAY** [comment]
@AnuragNishad12 there seems to be no traction on this issue. Are you still working on it?

**Comment by git-ashug** [comment]
If this is idle I can pick this up, let me know @AnuragNishad12 @mayorJAY

**Comment by git-ashug** [comment]
Yes @mayorJAY

**Comment by mayorJAY** [comment]
I'm assigning it to you now
