### ISSUE TITLE
Refactor WorkflowGroup API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#59]
We want to refactor the WorkflowGroup API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by sharmaudit124** [comment]
@mayorJAY can you assign this issue to me?

**Comment by mayorJAY** [comment]
Sure

**Comment by mayorJAY** [comment]
@sharmaudit124 there seems to be no traction on this issue. Are you still working on it?

**Comment by mayorJAY** [comment]
@sccalabr are you available to pick this up ASAP?
