### ISSUE TITLE
Refactor InboundParse API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#62]
We want to refactor the InboundParse API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by git-ashug** [comment]
Hi @mayorJAY , @unicodeveloper , I would like to work on this. Can you please assign this to me?

**Comment by mayorJAY** [comment]
Sure, give it a shot @git-ashug

**Comment by charan2628** [comment]
Hi @mayorJAY I already made a PR

**Comment by mayorJAY** [comment]
Kindly ensure that an issue is assigned to you before you begin implementation @charan2628

**Comment by git-ashug** [comment]
Will raise a PR for this by tomorrow EOD, dev in progress

**Comment by git-ashug** [comment]
Hi @mayorJAY , raised PR. Please review
