### ISSUE TITLE
Refactor Tenants API to conform to new design

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#66]
We want to refactor the Tenants API to address compatibility issues with Micronaut and Quarkus arising from the library's reliance on Spring framework.

We would like to have the Events API migrated to the new REST dependency and ensure the on going updates to the unit tests to validate the modifications and uphold code quality.

For guidance on the expected changes, kindly refer to this pull request #54.

PLEASE BRANCH OFF `STAGING` BRANCH AND ALL PRS SHOULD GO TO `STAGING` BRANCH FOR THESE CHANGES

**Comment by mslowiak** [comment]
Hello @mayorJAY @unicodeveloper  👋 
Can I work on this issue?

**Comment by mayorJAY** [comment]
Sure, give it a shot. I'm assigning it to you @mslowiak
