### ISSUE TITLE
Add Version Badge and Correct API Reference Link to ReadMe

### ISSUE THREAD

**Issue by mayorJAY** [novuhq/novu-java#83]
* **Add a badge that would display the current version of the SDK so as to make it visible to users**
![screenshot_badge](https://github.com/novuhq/novu-java/assets/37001871/b757ce3f-7a1c-47ec-9e50-25ccf404418a)

.
.
.

* **Link the correct URL to the API reference doc**
![screenshot_link](https://github.com/novuhq/novu-java/assets/37001871/3a24b33f-c9a2-4b95-aed9-2e2fb0bb3e96)

**Comment by ChenemiKen** [comment]
hello @mayorJAY, can you assign this issue to me?
